# Meta Arguments: What job? What train .py file? Base config? Where to store?
meta_job_args:
  project_name: "purerl-test"
  experiment_type: "hyperparameter-search"
  base_train_fname: "train_agents_for_paper.py"
  base_train_config: "train_stuff.yaml"
  experiment_dir: "experiment_dir"


# Parameters specific to the hyperparameter search
param_search_args:
  search_logging:
    max_objective: True
    aggregate_seeds: "mean"
    problem_type: "final"
    eval_metrics:
      - "return"
  search_resources:
    num_search_batches: 1
    num_evals_per_batch: 12
    num_seeds_per_eval: 1
  search_config:
    search_type: "Grid"
    search_schedule: "sync"
    search_params:
      categorical:
        env:
          # - reacher
          # - pusher
          # - hopper
          - swimmer
          # - halfcheetah
          # - ant
        algo:
          # - ppo
          # - sac
          - ddpg



# Parameters specific to an individual job
single_job_args:
  job_name: "train_agents"
  num_gpus: 1
  num_logical_cores: 4
  log_file: "log"
  err_file: "err"
  env_name: "jax"
  time_per_job: "00:08:00"
  partition:
    # - "ex_scioi_a100nv"
    - "ex_scioi_gpu"
    # - "gpu"
  gpu_type: a100
  memory_per_cpu: 10000
