ppo:
  env: CartPole-v1
  env_kwargs: null
  agent_kwargs:
    activation: tanh
  num_envs: 5
  num_steps: 100
  num_epochs: 5
  num_minibatches: 5
  learning_rate: 0.00075
  max_grad_norm: 0.5
  total_timesteps: 100_000
  eval_freq: 1000
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5

dqn:
  env: CartPole-v1
  env_kwargs: null
  agent: DuelingQNetwork
  agent_kwargs:
    activation: tanh
  num_envs: 1
  buffer_size: 50_000
  fill_buffer: 10_000
  batch_size: 100
  max_grad_norm: 10
  learning_rate: 0.0005
  gradient_steps: 1
  total_timesteps: 250_000
  eval_freq: 2500
  target_update_freq: 200
  eps_start: 1
  eps_end: 0.05
  exploration_fraction: 0.5
  gamma: 1.0
  ddqn: true

sac:
  env: CartPole-v1
  env_kwargs: null
  agent_kwargs:
    activation: tanh
  num_envs: 5
  buffer_size: 10_000
  fill_buffer: 1000
  batch_size: 256
  learning_rate: 0.001
  gradient_steps: 2
  total_timesteps: 50_000
  eval_freq: 500
  gamma: 0.99
  tau: 0.95
  target_entropy_ratio: 0.7

es:
  env: CartPole-v1
  num_generations: 5
  eval_freq: 1
  strategy: SNES
  strategy_kwargs:
    popsize: 50
  num_rollouts: 8
