# tuned
sac:
  env: brax/swimmer
  env_kwargs: null
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1_000_000
  fill_buffer: 10_000
  batch_size: 128
  learning_rate: 0.0005720796166976961
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.995
  tau: 0.95
  target_entropy_ratio: 0
  normalize_observations: true


# tuned
ppo:
  env: brax/swimmer
  agent_kwargs:
    activation: tanh
  num_envs: 128
  num_steps: 64
  num_epochs: 7
  num_minibatches: 8
  learning_rate: 0.002890766122997103
  max_grad_norm: 0.5
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.98
  gae_lambda: 0.99
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: true


# tuned
ddpg:
  env: brax/swimmer
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 512
  learning_rate: 0.000468696655640884
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 32768
  gamma: 0.995
  tau: 0.995
  max_grad_norm: 0.1
  exploration_noise: 0.9
