log_config:
  time_to_track: ["step"]
  what_to_track:
    - return
    - episode_length
  what_to_print:
    - return
    - return_std
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: purerl-test
    group: sweep-pusher-ddpg-128-envs
    entity: kerajli
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1

train_config:
  algo: ddpg
  num_seeds: 5

  env: brax/pusher
  env_kwargs:
    episode_length: 100
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 1048576
  fill_buffer: 8192
  batch_size: 256
  learning_rate: 0.0003
  gradient_steps: 128
  total_timesteps: 5242880
  eval_freq: 262144
  gamma: 0.99
  tau: 0.99
  max_grad_norm: 10
  exploration_noise: 0.2
